[workspace]
members = ["runner", "shared", "shaders/raster"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Shashank Singh <sshashank124@gmail.com>"]
repository = "https://github.com/sshashank124/tsunami"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.dev]
opt-level = 3
codegen-units = 16
lto = "thin"

[profile.dev.build-override]
opt-level = 3
codegen-units = 16
