cargo-features = ["edition2024"]

[package]
name = "glsl"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
glam = { workspace = true }
glsl_derive = { path = "../glsl_derive" }

[lints]
workspace = true
