cargo-features = ["edition2024"]

[package]
name = "renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
ash = { version = "0.37", features = ["linked"] }
bytemuck = { workspace = true }
glam = { workspace = true }
gpu-allocator = { version = "0.23", default-features = false, features = [ "vulkan" ] }
image = "0.24"
scene = { workspace = true }
shared = { workspace = true }
tobj = "4"
winit = "0.29"

[lints]
workspace = true

[build-dependencies]
shaderc = "0.8"
