[package]
name = "tonemap"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
glam = { workspace = true }
shared = { workspace = true }
spirv-std = { workspace = true }
