[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { workspace = true }
glam = { workspace = true, features = ["bytemuck", "serde"] }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
